"""update stock_prices with swing trading indicators

Revision ID: 2f2bbb7fbd01
Revises: 85900d0e6498
Create Date: 2026-01-27 14:24:33.005565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2bbb7fbd01'
down_revision: Union[str, Sequence[str], None] = '85900d0e6498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
