"""add stock_prices and trading_signals tables with momentum indicators

Revision ID: 85900d0e6498
Revises: e4ad6d9efa5c
Create Date: 2026-01-27 14:23:09.212060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85900d0e6498'
down_revision: Union[str, Sequence[str], None] = 'e4ad6d9efa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
